version: "3.1"
services:
  expressapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=7777
    volumes:
      - .:/home/node/app:rw
    ports:
      - "7777:7777"
